### ISSUE TITLE
DepositManager.Sol Observation

### ISSUE THREAD

**Issue by xlassix** [LighthouseWeb3/contracts#10]
-  ```addDeposit``` doesn't enforce a rate for the Volume of Storage Purchased

    the contract DepositManager doesn't seem to enforce any rate for a deposit, which implies anyone can call the contract with min eth. let's say 0.0000000000001 to request 1TB and another can use 0.000000000001 to request 1pb

- whitelisted addresses could be handled better with mappings 
for example 
mapping(address => bool) 
By default, any address lookup will be `false`. setting an address would be as easy as changing the flag to `true`.
then we can use a uint to keep track of the count of activeWhitelisted Addresses.  there is a tradeoff to either approach, depending on the rate at which the data will be updated. I would naturally not opt for a list if the data stored in it will be removed for any reason 

The same goes for  ```ProviderRegistry.sol```  **storage is expensive** on the blockchain

**Comment by nandit123** [comment]
These issues has already been resolved in `experimental` branch. Closing the issue. Thanks!
